### ISSUE TITLE
[Q] Is there a way to reflect the query in the URL?

### ISSUE THREAD

**Issue by amoutonbrady** [rturnq/solid-router#12]
Hey,

I'm running into an issue with get/search query parameters. Somehow when I navigate with a `<NavLink>` to something like `/path?test=value` it's well parsed and retrieved within the `useRouter()` as `router.query().test` but doesn't seem to be reflected in the URL.

Digging up a bit the code, I think this something within the [`handleRoute`](https://github.com/rturnq/solid-router/blob/master/src/routerContext.ts#L52) function that strips it but I couldn't really put my finger on it.

I'm wondering if this is something that's not implemented just yet or if I missed something?

[Here's a small reproduction.](https://codesandbox.io/s/query-lost-in-translation-ulo5n)

Thank you

**Comment by rturnq** [comment]
Yeah, this is an oversight on my part. The routing integrations `browerPathRouting` and `browserHashRouting` are only pushing/replacing the path and not the full path+query. I'll publish a fix shortly.

**Comment by rturnq** [comment]
I just published v0.1.6 which should resolve this. I also fixed an issue with the query parameters not being reactive.

**Comment by amoutonbrady** [comment]
You rock! I'll be sure to check it out.

Thanks again for your reactivity :)
