### ISSUE TITLE
opening hash link in new tab is broken

### ISSUE THREAD

**Issue by ozgrakkurt** [rturnq/solid-router#13]
Hi, first thanks for the library.
I have a problem with hash router.
Clicking this element with middle mouse button
```jsx
<Link class="btn btn-link ml-2" href="/monitor">
  Monitor
</Link>
```
which normally leads to: `http://localhost:8080/web-app#/monitor` opens a new tab with this address:  `http://localhost:8080/monitor`.
I would expect it to open a new tab with `http://localhost:8080/web-app#/monitor`. I tried both hashIntegration and history integration with createHashHistory but both behave this way. Is this a bug or how can I fix this?

**Comment by ozgrakkurt** [comment]
looks like inferno router ignores middle clicks: [code](https://github.com/infernojs/inferno/blob/master/packages/inferno-router/src/Link.ts#L26).
also same with react router: [code](https://github.com/ReactTraining/react-router/blob/085d0a862c33f9cfbbf825fddb643cbc0ed44243/packages/react-router-dom/modules/Link.js#L45).
should this be the default or is it possible to make it work like a normal link maybe?

**Comment by ozgrakkurt** [comment]
I think this just needs a makeHref function that will be used by <Links> to put hrefs into <a> elements instead of just using href prop

**Comment by rturnq** [comment]
Sorry for the slow reply. Yeah, I didn't consider that some integrations would need the href to be rendered differently in the link. The links should absolutely works as normal links, so I'll need to fix this and probably look at the target attribute as well. I guess this means the integration needs to be a little more than just a signal.

**Comment by rturnq** [comment]
Ok, check out v0.2.1. I added overridable path rendering and the onclick ignore logic from React Router. You shouldn't have to make any changes to your code.

**Comment by ozgrakkurt** [comment]
thank you, it works now.
