### ISSUE TITLE
NavLink homepage link is always active

### ISSUE THREAD

**Issue by Acidic9** [rturnq/solid-router#21]
I have setup the router and am creating a nav menu:
```jsx
<NavLink
  className="class-1"
  activeClass="class-2"
  href="/"
>
  Home
</NavLink>
<NavLink
  className="class-1"
  activeClass="class-2"
  href="/about"
>
  About
</NavLink>
```
When navigating to `/about`, the home link `/` still has `class-1 class-2`. I would expect `class-2` to not be present on the home link when I'm on `/about`.

**Comment by rturnq** [comment]
You'll need to add the `end` property to the home NavLink. This works the same as on a ShowRoute or MatchRoute component and tells it to only match if the path matches to the end of the current location.

```jsx
<NavLink
  className="class-1"
  activeClass="class-2"
  href="/"
  end  // <-- Add this
>
  Home
</NavLink>
```

**Comment by rturnq** [comment]
Closing as resolved.
