### ISSUE TITLE
[Feature request] async/lazy load route

### ISSUE THREAD

**Issue by beckend** [rturnq/solid-router#23]
for codesplitting.

**Comment by rturnq** [comment]
Can you elaborate what you are looking for from this feature? Solid currently supports [lazy loading](https://www.solidjs.com/docs/1.0.0#lazy) components and this works today with the router and to code split with popular build tools.

**Comment by beckend** [comment]
Oh, can you show some concrete code using this router?

**Comment by beckend** [comment]
I am talking about dynamic import statement, so if it's a big component, the bundles will be split.

**Comment by rturnq** [comment]
You can read more about [lazy](https://www.solidjs.com/docs/1.0.0#lazy), [Suspense](https://www.solidjs.com/docs/1.0.0#%3Csuspense%3E) and [transitions](https://www.solidjs.com/docs/1.0.0#usetransition) in the Solid docs, but here is a simple example that shows how they can be used with the router: https://codesandbox.io/s/solid-router-lazy-rgkjh

Essentially, you will import your component using a dynamic import via Solid's `lazy` function. Then you can just use them a routes and they will load when the route is made active the first time. Wrapping your routes (usually the root most) in a suspense boundary will let you have nice transitions while waiting for the next route to load. Obviously this requires your bundler to handle the actual code-splitting on dynamic imports but that is pretty standard.

**Comment by beckend** [comment]
Ok thanks for your time to comment!
